site_name: stz
dev_addr: '127.0.0.1:5555'

docs_dir: docs
site_dir: site
extra_css:
  - style.css

theme:
  name: material

  features:
    - content.code.copy
    - content.code.select

nav:
  - stz: index.md

  - Definitions:
    - 1. Types: definitions/01-types.md
    - 2. Range: definitions/02-range.md
    - 3. Log  : definitions/03-log.md

  - Fundamentals:
    - 1. Arena: fundamentals/01-Arena.md
    - 2. Slice: fundamentals/02-Slice.md
    - 3. Str  : fundamentals/03-Str.md
    - 4. Buf  : fundamentals/04-Buf.md
    - 5. Map  : fundamentals/06-Map.md
    - 6. Trie : fundamentals/07-Trie.md
    - 7. LTrie: fundamentals/08-LTrie.md
    - 8. Table: fundamentals/09-Table.md

  - Utilities:
    - 1. File : utilities/01-File.md
    - 2. Cmd  : utilities/02-Cmd.md
    - 3. Path : utilities/03-Path.md
    - 4. Db   : utilities/04-Db.md
    - 5. Gui  : utilities/05-Gui.md

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mermaid2
  - table-reader
