site_name: stz

nav:
  - Home: index.md

  - Definitions:
    - 1. Types  : definitions/01-types.md
    - 2. Range  : definitions/02-range.md
    - 3. Log    : definitions/03-log.md
    - 4. Doctest: definitions/04-doctest.md

  - Fundamentals:
    - 1. Arena: fundamentals/01-Arena.md
    - 2. List : fundamentals/02-List.md

docs_dir: docs
site_dir: site
dev_addr: '127.0.0.1:5555'
extra_css:
  - style.css

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mermaid2
  - table-reader
